services:
  dr-blythe-backend-db:
    image: postgres:16
    container_name: dr-blythe-backend-db
    environment:
      POSTGRES_USER: dr-blythe
      POSTGRES_PASSWORD: iset
      POSTGRES_DB: dr-blythe-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dr-blythe -d dr-blythe-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5433"