openapi: "3.0.0"
info:
  version: 0.0.1
  title: DR Blythe API
  description: API for DR Blythe management

paths:
  /patient:
    post:
      summary: create new patient
      operationId: createPatient
      tags:
        - Patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Patient"
      responses:
        "201":
          description: create a new Patient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
    get: 
      summary: get all patients
      operationId: getAllPatients
      tags: 
        - Patient
      responses:
        "200":
          description: list containing all patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Patient"

  /patient/{patientId}:
    get:
      summary: get existing patient
      operationId: getPatientById
      parameters:
        - in: path
          name: patientId
          schema: 
            type: string
            format: uuid
          required: true
          description: Id of the patient
      tags:
        - Patient
      responses: 
        "200":
          description: patient is retreived
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Patient"
    put: 
      summary: update an existing patient
      description: update an existing patient by Id
      operationId: updatePatient
      parameters:
        - in: path
          name: patientId
          schema: 
            type: string
            format: uuid
          required: true
          description: Id of the patient
      requestBody: 
        required: true
        content:
          application/json: 
            schema:
              $ref: "#/components/schemas/Patient"
      tags: 
        - Patient
      responses: 
        "200":
          description: patient updated
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Patient"
                
  /appointment:
    get: 
      summary: get all appointments
      operationId: getAllAppointments
      tags: 
        - Appointment
      responses:
        "200":
          description: list containing all appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"

components:
  schemas:
    Patient:
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        phone:
          type: string
        name:
          type: string
        emergencyContactName:
          type: string
        emergencyContactNumber:
          type: string
        insuranceProvider:
          type: string
        insurancePolicyNumber:
          type: string
        allergies:
          type: string
        currentMedication:
          type: string
        primaryConsent:
          type: boolean
        gender:
          type: string
        birthdate:
          type: string
          format: date
        address:
          type: string
        occupation:
          type: string
        familyMedicalHistory:
          type: string
        pastMedicalHistory:
          type: string
        identificationType:
          type: string
        identificationNumber:
          type: string
        identificationDocumentId:
          type: string
        identificationDocumentUrl:
          type: string
        primaryPhysician:
          type: string
          
    Appointment:
      properties:
        id:
          type: string
          format: uuid
        primaryPhysician:
          type: string
        reason:
          type: string
        note:
          type: string
        cancellationReason:
          type: string
        schedule:
          type: string
          format: date
        status:
          $ref: "#/components/schemas/Status"
    
    Status:
      type: string
      enum: 
        - ON 
        - OFF 